apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
# will work for all namespaces in the cluster
metadata:
  name: letsencrypt
spec:
  acme:
    email: jaspreetsingh1847@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx